server:
  port: 8080
  servlet:
    context-path: "/vue-admin-backend"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_admin_backend?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

# Druid 数据源配置，继承spring.datasource.* 配置，相同则覆盖
    datasource:
      druid:
        initial-size: 2
        max-active: 30
        min-idle: 2
        max-wait: 1234
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 5
        validation-query: select 1
        validation-query-timeout: 1
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
        time-between-eviction-runs-millis: 10000
        min-evictable-idle-time-millis: 30001
        async-close-connection-enable: true
        aop-patterns: com.alibaba.druid.spring.boot.demo.service.*

  # 配置下面参数用于启动监控页面，考虑安全问题，默认是关闭的，按需开启
        stat-view-servlet.enabled: true
        filter.stat.enabled: true
        web-stat-filter.enabled: true
