server:
  port: 8080
  servlet:
    context-path: "/vue-admin-backend"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_admin_backend?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

# Druid 数据源配置，继承spring.datasource.* 配置，相同则覆盖
    datasource:
      druid:
        initial-size: 2
        max-active: 30
        min-idle: 2
        max-wait: 1234
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 5
        validation-query: select 1
        validation-query-timeout: 1
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
        time-between-eviction-runs-millis: 10000
        min-evictable-idle-time-millis: 30001
        async-close-connection-enable: true
        aop-patterns: com.alibaba.druid.spring.boot.demo.service.*

  # 配置下面参数用于启动监控页面，考虑安全问题，默认是关闭的，按需开启
        stat-view-servlet.enabled: true
        filter.stat.enabled: true
        web-stat-filter.enabled: true

mybatis-plus:
  #mapper路径
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: false
    #懒加载
    #aggressive-lazy-loading: true
    #NONE：不启用自动映射 PARTIAL：只对非嵌套的 resultMap 进行自动映射 FULL：对所有的 resultMap 都进行自动映射
    #auto-mapping-behavior: partial
    #NONE：不做任何处理 (默认值)WARNING：以日志的形式打印相关警告信息 FAILING：当作映射失败处理，并抛出异常和详细信息
    #auto-mapping-unknown-column-behavior: none
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: auto
      #是否开启大写命名，默认不开启
      #capital-mode: false
      #逻辑已删除值,(逻辑删除下有效) 需要注入逻辑策略LogicSqlInjector 以@Bean方式注入
      logic-not-delete-value: 0
      #逻辑未删除值,(逻辑删除下有效)
      logic-delete-value: 1

##jwt配置
jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: "jwtSecret"
  iss: "fang"
  expiration: 3600000

